@echo off
echo The installation has started...

echo Creating a virtual environment...
call python -m venv .venv
call .venv\Scripts\activate.bat
echo A virtual environment has been created and activated...

echo The installation of requirements has begun...
call python -m pip install --upgrade pip
call pip install -r requirements.txt
echo The installation of requirements has been completed...
